const ProductJSON = [
  {
    title: "XBox Elite Controller",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.",
    images: [
      {
        fileId: "62400d4d7ade14703df51af1",
        name: "bose-headphones_ImC6hyvwO.png",
        size: 145729,
        filePath: "/habitual-ecommerce/bose-headphones_ImC6hyvwO.png",
        url: "https://ik.imagekit.io/imashish/habitual-ecommerce/xbox-controller_3JJaRBQMv.png",
        fileType: "image",
        height: 426,
        width: 284,
        thumbnailUrl:
          "https://ik.imagekit.io/imashish/habitual-ecommerce/xbox-controller_3JJaRBQMv.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647570751254",
        AITags: null,
      },
    ],
    variants: null,
    slideColors: [],
    price: 300,
    discount: 10,
    quantity: 100,
    categoryIds: ["6233f4220315ad5d844cfa00"],
    isStaffPick: false,
    isFeatured: false,
  },
  {
    title: "Bose Headphones",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.",
    images: [
      {
        fileId: "62400d4d7ade14703df51af1",
        name: "bose-headphones_ImC6hyvwO.png",
        size: 145729,
        filePath: "/habitual-ecommerce/bose-headphones_ImC6hyvwO.png",
        url: "https://ik.imagekit.io/imashish/habitual-ecommerce/bose-headphones_ImC6hyvwO.png",
        fileType: "image",
        height: 426,
        width: 284,
        thumbnailUrl: "https://ik.imagekit.io/imashish/tr:n-media_library_thumbnail/habitual-ecommerce/bose-headphones_ImC6hyvwO.png",
        AITags: null,
      },
    ],
    variants: null,
    slideColors: [],
    price: 265.99,
    discount: 10,
    quantity: 100,
    categoryIds: ["6233f4220315ad5d844cfa00"],
    isStaffPick: false,
    isFeatured: false,
  },
  {
    title: "Oculus Rfit",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.",
    images: [
      {
        fileId: "62400d4d7ade14703df51af1",
        name: "bose-headphones_ImC6hyvwO.png",
        size: 145729,
        filePath: "/habitual-ecommerce/vr_crqK2iyqW.png",
        url: "https://ik.imagekit.io/imashish/habitual-ecommerce/vr_crqK2iyqW.png",
        fileType: "image",
        height: 426,
        width: 284,
        thumbnailUrl: "https://ik.imagekit.io/imashish/tr:n-media_library_thumbnail/habitual-ecommerce/vr_crqK2iyqW.png",
        AITags: null,
      },
    ],
    variants: null,
    slideColors: [],
    price: 265.99,
    discount: 10,
    quantity: 100,
    categoryIds: ["6233ef3f963cc01b8a952fd2", "6233f4220315ad5d844cfa00"],
    isStaffPick: false,
    isFeatured: false,
  },
  {
    title: "Apple 13” Macbook Pro",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.",
    images: [
      {
        fileId: "62400d4d7ade14703df51af1",
        name: "bose-headphones_ImC6hyvwO.png",
        size: 145729,
        filePath: "/habitual-ecommerce/mac.png",
        url: "https://ik.imagekit.io/imashish/habitual-ecommerce/mac.png",
        fileType: "image",
        height: 426,
        width: 284,
        thumbnailUrl: "https://ik.imagekit.io/imashish/tr:n-media_library_thumbnail/habitual-ecommerce/mac.png",
        AITags: null,
      },
    ],
    variants: null,
    slideColors: [],
    price: 265.99,
    discount: 10,
    quantity: 100,
    categoryIds: ["6233f4220315ad5d844cfa00"],
    isStaffPick: false,
    isFeatured: false,
  },
  {
    title: "LG UltraWide 4k Display",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.",
    images: [
      {
        fileId: "62400d4d7ade14703df51af1",
        name: "bose-headphones_ImC6hyvwO.png",
        size: 145729,
        filePath: "/habitual-ecommerce/mac.png",
        url: "https://ik.imagekit.io/imashish/habitual-ecommerce/Electronics_01_K9iLL9h9E.png",
        fileType: "image",
        height: 426,
        width: 284,
        thumbnailUrl: "https://ik.imagekit.io/imashish/habitual-ecommerce/Electronics_01_K9iLL9h9E.png",
        AITags: null,
      },
    ],
    variants: null,
    slideColors: [],
    price: 265.99,
    discount: 10,
    quantity: 100,
    categoryIds: ["6233f4220315ad5d844cfa00"],
    isStaffPick: false,
    isFeatured: false,
  },
  {
    title: "“Awaken, My Love!”",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.",
    images: [
      {
        fileId: "62400d4d7ade14703df51af1",
        name: "bose-headphones_ImC6hyvwO.png",
        size: 145729,
        filePath: "/habitual-ecommerce/mac.png",
        url: "https://ik.imagekit.io/imashish/habitual-ecommerce/music-01.png",
        fileType: "image",
        height: 426,
        width: 284,
        thumbnailUrl: "https://ik.imagekit.io/imashish/habitual-ecommerce/music-01.png",
        AITags: null,
      },
    ],
    variants: null,
    slideColors: [],
    price: 265.99,
    discount: 10,
    quantity: 100,
    categoryIds: ["6233f43b0315ad5d844cfa01"],
    isStaffPick: false,
    isFeatured: false,
  },
  {
    title: "Dark Lane Demo Tapes",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.",
    images: [
      {
        fileId: "62400d4d7ade14703df51af1",
        name: "bose-headphones_ImC6hyvwO.png",
        size: 145729,
        filePath: "/habitual-ecommerce/mac.png",
        url: "https://ik.imagekit.io/imashish/habitual-ecommerce/music-02.png",
        fileType: "image",
        height: 426,
        width: 284,
        thumbnailUrl: "https://ik.imagekit.io/imashish/habitual-ecommerce/music-02.png",
        AITags: null,
      },
    ],
    variants: null,
    slideColors: [],
    price: 265.99,
    discount: 10,
    quantity: 100,
    categoryIds: ["6233f43b0315ad5d844cfa01"],
    isStaffPick: false,
    isFeatured: false,
  },
  {
    title: "4 Your Eyez Only",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.",
    images: [
      {
        fileId: "62400d4d7ade14703df51af1",
        name: "bose-headphones_ImC6hyvwO.png",
        size: 145729,
        filePath: "/habitual-ecommerce/mac.png",
        url: "https://ik.imagekit.io/imashish/habitual-ecommerce/music-03.png",
        fileType: "image",
        height: 426,
        width: 284,
        thumbnailUrl: "https://ik.imagekit.io/imashish/habitual-ecommerce/music-03.png",
        AITags: null,
      },
    ],
    variants: null,
    slideColors: [],
    price: 265.99,
    discount: 10,
    quantity: 100,
    categoryIds: ["6233f43b0315ad5d844cfa01"],
    isStaffPick: false,
    isFeatured: false,
  },
];

export default ProductJSON;
